### ISSUE TITLE
Incorrect amount of speakers worldwide for languages

### ISSUE THREAD

**Issue by bicolino34** [hugolpz/LanguagesGallery#6]
Ukrainian language is shown to have 27M speakers worldwide while in reality about 40M use it.
German is shown to have 77M while in reality it is about 140M.
It seems that there are problems with this number in a lot of languages

---- 
[EDIT] Issue closes, the following were disccussed.
- [x] Wikidata inconsistency for Speakers (P1098) : native or all.
- [x] Speaker of Ukrainian : 27M according to ethnologue.
- [x] Better legend need to be coded / designed, issue #10 opened.

**Comment by hugolpz** [comment]
@bicolino34 , you may dive into the SPARQL query folder for details, namely [sparql/WD-LanguagesPopulation.sparql](https://github.com/hugolpz/Sparql2Data/blob/main/sparql/WD-LanguagesPopulation.sparql). From memory, there are the issues we have with de source data on Wikidata:

1. property used is about **native** speakers
2. data isnt consistent : a) not up to date or b) confusing native and overall speakers depending on the language.

Also, the gallery currently has no displayed legend explaining the various dimensions. Only the Github README.md contains a minimal legend.

Overall, there is further work to do to explain and enrich and polish this page indeed.

But i now moved to other projects needing my push to move forward.

**Comment by bicolino34** [comment]
Ukrainian has about 37 millions native speakers. I will check whether there is a mistake in wikidata items when I have time

**Comment by hugolpz** [comment]
A source may say 1/3 of 2010 Ukrainians (40M) answered to be Russian speakers first. But i wonder if that was true. And i'm pretty sure it's incorrect now. I believe the language population data requires review and update from linguistic sources. cc @pamputt

**Comment by pamputt** [comment]
I am not aware about a lot of sources giving the number of speaker for a large quantity of languages. The two I know are Ethnologue and UNESCO WAL (Sorosoro provides also an estimation of the number of speakers but it covers less languages than the two other websites ; for example Ukrainian is not described). Checking again theses two websites, I discovered they have changed they way to present the number of speaker. Both websites now use a range that give the order of magnitude (i.e. for the Ukrainian language, the number of speakers range from 10 M to 100 M : [Ethnologue](https://www.ethnologue.com/language/ukr/#population), [WAL](https://en.wal.unesco.org/languages/ukrainian)). 

The number of speakers is really difficult to estimate. It depends for example if one considers only L1 speakers or all speakers. So I am not sure we will be able to find a "reliable" number for a large quantity of language

**Comment by hugolpz** [comment]
> Ukrainian has about 37 millions native speakers. I will check whether there is a mistake in wikidata items when I have time

@bicolino34 , as for the amount of native speakers, I think it's settle since https://wikidata.org/wiki/Q8798#P1098's 27M statement has a credible source (ethnologue). It don't think it's accurante, we heard about radical changes in term of self identification with Russophones now moving toward declaring themselves Ukrainophones in Ukraine. And likely the opposite movement in Russia. The situation obviously wont allow any better estimate for a decade I guess.

I close this issue, which should mostly be discussed on Wikidata.
